template = "https://github.com/giellalt/template-lang-und"
rev_id = 283
template_sha = "bfef967c632b9041975725ec13da8c2dfe66b74e"

[replacements]
__GLOTTOLOG_ID__ = "klin1234"
__REPO__ = "lang-tlh"
__UND2C__ = "tlh"
__UNDEFINED__ = "Klingon"
__UND__ = "tlh"
