template = "https://github.com/giellalt/template-lang-und"
rev_id = 287
template_sha = "15a8cf1917db1d48c56f7254ed58b4e74a6fcd9c"

[replacements]
__GLOTTOLOG_ID__ = "klin1234"
__REPO__ = "lang-tlh"
__UND2C__ = "tlh"
__UNDEFINED__ = "Klingon"
__UND__ = "tlh"
