template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "b019fafa945ec21f8f1ee983a95aba800ec89260"

[replacements]
__GLOTTOLOG_ID__ = "klin1234"
__REPO__ = "lang-tlh"
__UND2C__ = "tlh"
__UNDEFINED__ = "Klingon"
__UND__ = "tlh"
